services:
  - type: web
    name: ai-screening
    env: static
    staticPublishPath: interview_ui
    headers:
      - path: "/*.wasm"
        name: Content-Type
        value: application/wasm

      - path: "/*.data"
        name: Content-Type
        value: application/octet-stream

      - path: "/*.binarypb"
        name: Content-Type
        value: application/octet-stream

      - path: "/*"
        name: Cross-Origin-Embedder-Policy
        value: require-corp

      - path: "/*"
        name: Cross-Origin-Opener-Policy
        value: same-origin
